config1/config1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls), #127.0.0.1:8000/admin
    path('polls/', include('polls.urls')), #127.0.0.1:8000/polls
    path('member/', include('member.urls')), #127.0.0.1:8000/member
    # path('polls/', include('member.urls)), #127.0.0.1:8000/member
]

config1/member/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('insert/', views.insert), #127.0.0.1:8000/member/insert   
]

config1/polls/urls.py
from django.urls import path
from django.urls import include
from . import views

app_name='polls'
urlpatterns = [
    # path(url패턴, url이 매칭되면 호출되는 뷰함수와 인자[, 이름]),
    path('', views.index, name='list'), #127.0.0.1:8000/polls
    path('<int:qid>/', views.detail, name='detail'), #127.0.0.1:8000/polls/2
    path('vote/<int:qid>/', views.vote, name='vote1'),
    path('dbtest/', views.dbtest),
    # path('insert/', views.insert), #127.0.0.1:8000/polls/insert
]

config1/board/models.py
from django.db import models

# class Board(models.Model):
#     title = models.CharField(max_length = 10)
#     username = models.CharField(max_length = 10)
#     pw = models.CharField(max_length = 10)
#     regdate = models.DateTimeField(auto_now_add = True) #저장시점에 시간을 자동저장
#     # id 칼럼이 추가, 기본키, 자동 증가

config1/member/models.py
from django.db import models

class Member(models.Model):
    username = models.CharField(max_length = 50, verbose_name='사용자 이름')
    pw = models.CharField(max_length = 50, verbose_name='비밀번호')
    email = models.CharField(max_length = 50, verbose_name='이메일 주소')
    hp = models.CharField(max_length = 50, verbose_name='휴대폰번호')
    regdate = models.DateTimeField(auto_now_add = True, verbose_name='등록일')
    
    def __str__(self):
        return self.username+'-'+self.hp

    class Meta:
        db_table='member'

config1/polls/models.py
from django.db import models

# 테이블 -> 하나의 클래스
# 테이블의 컬럼 -> 클레스의 변수
# 기본키 컬럼은 id로 자동 생성
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    
    # toString()
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    # 외래키 제약 설정
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

config1/board/views.py
from django.shortcuts import render

# Create your views here.

config1/member/views.py
from django.shortcuts import render
from .models import Member
# 비밀번호 암호화
from django.contrib.auth.hashers import make_password

def insert(request):
    if request.method == 'GET':
        return render(request, 'insert.html') #127.0.0.1:8000/member/insert --get 방식
    elif request.method == 'POST':
        username = request.POST['username']
        pw = request.POST['pw']
        pw1 = request.POST['pw1']
        email = request.POST['email']
        hp = request.POST['hp']
        msg = {}

        if not (username and pw and pw1 and hp):
            msg['err'] = '필수 입력 값을 채우세요'
        elif pw != pw1:
            msg['err'] = '비밀번호를 확인하세요!'
        else:
            m = Member(username=username, pw=make_password(pw), email=email, hp=hp)
            m.save()
        return render(request, 'insert.html', msg)

config1/polls/views.py
from .models import Question
from django.shortcuts import render
from django.shortcuts import get_object_or_404

def index(request):
    qlist = Question.objects.all()
    return render(request, 'polls/index.html', {'qlist' : qlist})
    # return render(request, 'polls/index.html') 
    # render(요청, 반환할 페이지[, 딕셔너리])

def detail(request, qid):
    # q = Question.objects.get(id=qid)
    # select * from question where id=qid
    q = get_object_or_404(Question, id=qid)
    c = q.choice_set.all()
    print(len(c))
    msg = {}
    msg['q']=q
    if len(c) < 1:
        msg['err'] = '선택할 항목이 없습니다'
    return render(request, 'polls/detail.html', msg)

def vote(request, qid):
    q = Question.objects.get(id=qid)
    # q = get_object_or_404(Question, id=qid)
    cid = request.POST['choice']
    c = q.choice_set.get(id=cid)
    c.votes = c.votes+1
    c.save()
    return render(request, 'polls/result.html', {'q': q})
    # Question과 Choice는 1:N 관계, 외래키로 연결된 경우 모델소문자_set 속성이 제공됨

def dbtest(request):
    # 1) 삽입, 수정 save()
    # q = Question(question_text='좋아하는 운동은', pub_date='2021-01-07')
    # q.save()
    # q = Question(id=1, question_text='싫어하는 색은', pub_date='2021-01-07')
    # q.save()
    # return render(request, 'polls/dbtest.html')
    # 2) 조회
    # qlist= Question.objects.all() # 모든 데이터
    # qlist=Question.objects.get(id=3) # 조건에 맞는 데이터
    # print(qlist)

    # return render(request, 'polls/dbtest.html') 
    # return render(request, 'polls/dbtest.html', {'aa':'bb'}) # 127.0.0.1:8000/polls/dbtest
    # qlist= Question.objects.all() # 모든 데이터
    # return render(request, 'polls/dbtest.html', {'qlist': qlist})

    # 3) 삭제 delete()
    q = Question.objects.get(id=1)
    q.delete()

    return render(request, 'polls/dbtest.html')

config1/member/templates/insert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
    <link rel="stylesheet" href="/static/spring.css">
</head>
<body>
    <h1>insert.html</h1> <!--http://127.0.0.1:8000/member/insert-->
    <h2>{{err}}</h2>
    <form method="post" action=".">
    {%csrf_token%}
    <!--반드시 폼태그 내에 작성, 비정상적 접근을 막기위해 암호화된 키를 만듦, 장고에서는 필수-->
        <p>사용자 이름 <input type="text" name="username" id="username"></p>
        <p>비밀번호 <input type="password" name="pw" id="pw"></p>
        <p>비밀번호 확인 <input type="password" name="pw1" id="pw1"></p>
        <p>이메일 <input type="text" name="email" id="email"></p>
        <p>휴대폰 번호 <input type="text" name="hp" id="hp"></p>
        <p><input type="submit" value="등록"></p>
    </form>
</body>
</html>

config1/polls/templates/polls/dbtest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>dbtest.html</h1>
<hr>
<h2></h2> <!--변수의 값 출력-->
{% if qlist %}
    <ul>
    {% for q in qlist %}
        <li>{{q.id}} - {{q.question_text}}</li>
    {% endfor%}
    </ul>
{%else%}
    <p>자료없음</p>
{%endif%}
</body>
</html>

config1/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/spring.css">
</head>
<body>
    <h1>detail.html</h1>
    <hr>
    <h3>{{q.question_text}} - {{q.pub_date}}</h3>
    <!--Question과 Choice는 1:N 관계, 외래키로 연결된 경우 모델소문자_set속성이 제공됨 즉)q.choice_set.all()
    템플릿 문법상 () 생략-->
    {% if err %}
        <h3>{{err}}</h3>
    {% else %}
        <form method="POST" action="{%url 'polls:vote1' q.id%}">
        {%csrf_token%}
        {% for c in q.choice_set.all%}
            <input type="radio" name="choice" value="{{c.id}}">
            {{c.choice_text}}
            <br>
        {% endfor %}
            <input type="submit" value="투표하기">
        </form>
    {% endif %}
</body>
</html>

config1/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/spring.css">
</head>
<body>
<h1>index.html</h1>
<hr>
{% if qlist %}
<ul>
    {% for q in qlist %}
        <!--127.0.0.1/polls/2 ==> /polls/{{q.id}} -->
        <li><a href="/polls/{{q.id}}/">{{q.id}} - {{q.question_text}}</a></li>
    {% endfor %}
</ul>
{% else %}
    <p>자료없음</p>
{% endif %}
</body>
</html>

config1/polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>result.html</h1>
    <hr>
    <h3>{{q.question_text}}</h3>
    <ul>
        {% for c in q.choice_set.all %}
        <li>
            {{c.choice_text}} - {{c.votes}}
        </li>
        {% endfor %}
    </ul>
    <hr>
    <a href="{% url 'polls:list'%}">목록으로</a>
</body>
</html>