config2/books/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'books'

urlpatterns = [
    path('book/', views.BookList.as_view(), name='booklist'),
    path('publisher/', views.PublisherList.as_view(), name='publisherlist'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisherdetail'),
    path('', views.BooksIndexView.as_view(), name='index'),
    path('publisher/insert', views.PublisherCreate.as_view(), name='publisherinsert')
]
# as_view() 메소드 -  진입메소드,
# urls.py에서 클래스형 뷰의 as_view() 메소드를 호출

config2/config2/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
]

config2/books/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    addr = models.CharField(max_length=100)
    website = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('publisher', on_delete=models.CASCADE)
    pubdate = models.DateField()
    def __str__(self):
        return self.title

class Author(models.Model):
    name  = models.CharField(max_length=50)
    intro = models.CharField(max_length=100)
    email = models.EmailField()
    def __str__(self):
        return self.name

config2/books/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from .models import Book, Publisher, Author
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView

class BookList(ListView):
    model = Book

class PublisherList(ListView):
    model = Publisher

class PublisherDetail(DetailView):
    model = Publisher

class PublisherCreate(CreateView):
    model = Publisher
    fields = ['name', 'addr', 'website'] # 입력 받을 컬럼 지정
    template_name = 'books/publisherinsert.html'
    success_url = '/books' # CreateView, UpdateView, DeleteView를 사용시 특정 기능 수행 후 어떤 페이지로 이동할지 지정

class BooksIndexView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mlist']=['book', 'publisher', 'author']
        return context

config2/books/templates/books/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>books/book_list.html</h1>
    <hr>
    <ul>
    {% for b in object_list %}
        <li>{{b.title}} - {{b.publisher}}</li>
    {% endfor %}
    </ul>
</body>
</html>

config2/books/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>books/index.html</h1>
    <hr>
    <ul>
        {% for m in mlist %}
            <li><a href="/books/{{m}}">{{m}}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

config2/books/templates/books/publisher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>books/publisher_detail.html</h1>
    <hr>
    <p>출판사명 : {{object.name}}</p>
    <p>위치 : {{object.addr}}</p>
    <p>홈페이지 : {{object.website}}</p>
    <hr>
    <!-- <a href="/books/publisher">출판사 목록</a> -->
    <a href="{% url 'books:publisherlist' %}">출판사 목록</a>
</body>
</html>

config2/books/templates/books/publisher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>books/publisher_list.html</h1>
    <hr>
    <ul>
        {% for p in object_list %}
            <li><a href="{% url 'books:publisherdetail' p.id %}">{{p.name}}</a> - {{p.addr}}</li>
        {% endfor %}
    </ul>
    <hr>
    <a href="{% url 'books:index' %}">홈으로</a> 
    <a href="{% url 'books:publisherinsert' %}">출판사 등록</a>
</body>
</html>

config2/books/templates/books/publisherinsert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>publisherinsert.html</h1>
    <!-- {{form.as_p}}     -->
    <!-- {{form.as_ul}} -->
    <hr>
    <form id="frm1" method="POST">
        {% csrf_token %}
        <table border="1">
            {{form.as_table}} <!-- form.as_p, form.as_ul, form.as_table-->
            <tr>
                <td colspan="2"><input type="submit" value="등록"></td>
            </tr>
        </table>
    </form>
</body>
</html>